apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  values:
    global:
      istioNamespace: platform
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          # limits:
          #   memory: 765Mi
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            ports:
              - name: status-port
                protocol: TCP
                port: 15021
                targetPort: 15021
              - name: http2
                protocol: TCP
                port: 80
                targetPort: 8080
              - name: https
                protocol: TCP
                port: 443
                targetPort: 8443
          serviceAnnotations:
            external-dns.alpha.kubernetes.io/hostname: "*.k8s.kieranbamforth.me"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-gateway-cert
spec:
  secretName: default-gateway-cert-secret
  dnsNames:
    - "*.k8s.kieranbamforth.me"
  issuerRef:
    name: letsencrypt-prod-issuer
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
spec:
  selector:
    istio: ingressgateway
    app: istio-ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: default-gateway-cert-secret
    hosts:
    - "*.k8s.kieranbamforth.me"
  # - port:
  #     number: 80
  #     name: http
  #     protocol: HTTP
  #   hosts:
  #   - "*"
