
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - ../base
  - ./load-balancer/metallb.yml
  - ./load-balancer/configmap.yml

patchesStrategicMerge:
  - ./observability/metrics-server.yml
