apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - ./namespace.yml
  - ./operators/prometheus.yml
  - ./operators/prometheus-fix-permissions.yml
  - ./observability/prometheus.yml
  - ./observability/metrics-server.yml
  - ./observability/grafana.yml
  - ./observability/node-exporter.yml
  - ./cert-manager/cert-manager.yml
  - ./cert-manager/issuer.yml
  - ./external-dns.yml
  - ./operators/istio.yml
  - ./istio/istio.yml
  - ./external-services.yml

patchesStrategicMerge:
  - ./operators/istio-drop-namespace.yml
  - ./operators/istio-operator-container.yml
