apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hello@kieranbamforth.me
    privateKeySecretRef:
      name: letsencrypt-prod-secret
    solvers:
      - dns01:
          route53:
            region: eu-central-1
            accessKeyID: AKIA4OIUEYLURFCT37YE
            secretAccessKeySecretRef:
              name: cert-mgr-secret
              key: AWS_SECRET_ACCESS_KEY
