apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator-fix
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - list
- apiGroups:
  - ""
  resources:
    - nodes
    - nodes/metrics
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-fix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-fix
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: default
