apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: platform
spec:
  serviceAccountName: prometheus-operator
  serviceMonitorSelector:
    matchLabels:
      team: platform
  resources:
    requests:
      memory: 400Mi
      cpu: 50m
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    prometheus: platform
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9090
